---
language: go
env:
  - tf_version=0.12.26

branches:
  only:
  - master

go:
  - 1.12.x
  - master

before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

script:
  - make clean
  - curl -sfL https://git.io/goreleaser | sh -s -- --skip-publish --snapshot
  - env GO111MODULE=on 
  - make copyplugins 
  - make test