---
language: go

go:
  - 1.12.x
  - master

script:
  - make clean
  - curl -sfL https://git.io/goreleaser | sh -s -- --skip-publish --snapshot
  - env GO111MODULE=on 
  - make copyplugins 
  - make test