name: acceptance tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.13.0
        terraform_wrapper: false

    - name: Run test
      run: go test -v ./... | awk '!/\[no test files\]/ {print}' 

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cp.out
        name: codecov-umbrella
        fail_ci_if_error: false